function drawScene( tfMatRobotToCamera,...
                    tfMatRobotToEndeffector,...
                    tfMatRobotToNeedletip,...
                    tfEntryPoint,...
                    windowPoseInRobot,...
                    tumorPoseInRobot,...
                    tfMatEndeffectorToEntrypoint)
    figure;
%DRAWSCENE creates a 3d visualisation
	tfWindow = tfEntryPoint; tfWindow(:,4) = windowPoseInRobot;
    tfTumor  = tfEntryPoint; tfTumor(:,4)  = tumorPoseInRobot;
    % draw the coordinate frames
    drawCoordFrame(eye(4),                          'Robot');
    drawCoordFrame(tfMatRobotToCamera,              'Camera');
    drawCoordFrame(tfMatRobotToEndeffector,         'EndEffector');
    drawCoordFrame(tfMatRobotToNeedletip,           'Needletip');
    drawCoordFrame(tfEntryPoint,                    'Entrypoint');
    drawCoordFrame(tfWindow,                        'Window');
    drawCoordFrame(tfTumor,                         'Tumor');
    drawCoordFrame(tfMatEndeffectorToEntrypoint,    'Desired EndEffector');
    % draw the needle
    plot3([tfMatRobotToEndeffector(1,4) tfMatRobotToNeedletip(1,4)],...
          [tfMatRobotToEndeffector(2,4) tfMatRobotToNeedletip(2,4)],...
          [tfMatRobotToEndeffector(3,4) tfMatRobotToNeedletip(3,4)],...
          'LineWidth',3,'Color','k');
    hold on;
    % draw the desired needle
    plot3([tfMatEndeffectorToEntrypoint(1,4) tfEntryPoint(1,4)],...
          [tfMatEndeffectorToEntrypoint(2,4) tfEntryPoint(2,4)],...
          [tfMatEndeffectorToEntrypoint(3,4) tfEntryPoint(3,4)],...
          'LineWidth',3,'Color','r');
    % draw the movement line (between window and tumor)  
    v =  windowPoseInRobot - tumorPoseInRobot;
    p1 = tumorPoseInRobot + 10*v;
    plot3([p1(1) tumorPoseInRobot(1)],...
          [p1(2) tumorPoseInRobot(2)],...
          [p1(3) tumorPoseInRobot(3)],'k--');
    % draw the table
    patch( [-500 -500 500 500 -500], [-500 500 500 -500 -500], [0 0 0 0 0] );
    axis equal; % ?
    xlabel('robot X'); ylabel('robot Y'); zlabel('robot Z');
end